#+INCLUDE: theme/style.org
#+TITLE: org-wiki 
#+AUTHOR: Caio Rodrigues 


* Org-wiki 
** Overview 

Org-wiki is a wiki built on top of org-mode. It provides many functions to
keep a wiki and several notes.

It provides a custom protocol ~wiki:keyword~ which creates like. When
clicked this links creates the wiki file in the wiki directory with
name ~keyword.org~.

*Warning*: The screenshots aren't showed in this file because github
unfortunately doesn't render org-mode files with pictures yet. To see
the documentation with all pictures open the [[https://caiorss.github.io/org-wiki][html documentation]] .

Link formats:

 - =wiki:<pagename>=

Example: 

#+BEGIN_SRC org 
    wiki:Linux 
or 
    [[wiki:Linux]]
or
    [[wiki:Linux][Linux]]  
#+END_SRC

 - =wiki-asset-sys:<pagename>/<asset file name>=

Example: 

#+BEGIN_SRC org
     wiki-asset-sys:Linux;LearnLinux.pdf
or 
     [[wiki-asset-sys:Linux;LearnLinux.pdf]]
or
     [[wiki-asset-sys:Linux;LearnLinux.pdf][Book Learn Linux.pdf]]
#+END_SRC

It will open the file =~/wiki-directory/Linux/LearnLinux.pdf= with the
default system application.


Features:

 - A wiki system for Emacs

 - Command to export all pages to html without block Emacs.

 - Helm interface to search wiki pages.

 - Almost self-contained and with few dependencies.


# - Command to paste images (Only works in Linux for now and requires Xclip);

** Repository

| Repository         | https://github.com/caiorss/org-wiki |
| Html documetnation | https://caiorss.github.io/org-wiki/ |
|                    |                                     |

** Commands

  - =M-x org-wiki/index= - Open the index page. It opens the file
    index.org that is the first default page of the wiki. If the file
    doesn't exist it will be created.


  - =M-x org-wiki/index-frame= - Open the wiki index page in a new frame.


  - =M-x org-wiki/helm= - Open a helm interface to search the wiki
    page.

  
  - =M-x org-wiki/helm-frame= - Open a wiki page in a new frame. 


  - =M-x org-wiki/make-page= - Creates a new wiki page asking the user
    for the page name.


  - =M-x org-wiki/helm-assets= - Select a wiki page and open its
    assets directory.


  - =M-x org-wiki/dired= - Open the wiki directory in Emacs
    dired-mode showing only *.org files.


  - =M-x org-wiki/dired-all= - Open the wiki directory in Emacs
    showing all files. 


  - =M-x org-wiki/close= - Close all wiki pages.


  - =M-x org-wiki/insert= - Inserts a org-mode link at current point
    to a Wiki page selected through a helm-menu.
 
 - =M-x org-wiki/search-pattern= - Search all wiki page that contains
   a pattern. (string or regex pattern).

  - =M-x org-wiki/export-html-async= - Exports all wiki pages to html
    asynchronously, it means withoyt block Emacs by starting a new
    Emacs process in background.
** Setup 

1. Copy the package to the desired location. 


#+BEGIN_SRC sh 
mkdir -p ~/.emacs.d/packages/ 

cd ~/.emacs.d/packages/ 

git clone  https://github.com/caiorss/org-wiki

mkdir -p ~/org/wiki    # Make wiki location. 
#+END_SRC


2. Add to init file ~/.emacs.d/init.el or ~/.emacs 

#+BEGIN_SRC elisp 
(add-to-list 'load-path "~/.emacs.d/packages/org-wiki")
(require 'org-wiki)
(setq org-wiki/location "~/org/wiki")

#+END_SRC

** Screenshots 

 - 1. Command =M-x org-wiki/index= Open the wiki index page (file index.org) 

file:images/org-wiki-index.png

 - 2. Command =M-x org-wiki/helm= Open a helm menu to select the wiki
   page to be opened. 

file:images/wiki-helm-command.png 

 - 3. =M-x org-wiki/ [tab]= provides easy completion and
   discoverability to org-wiki commands. 

file:images/autocompletion.png 

 - 4. =M-x org-wiki/dired= Open the org-wiki directory showing only
   the wiki pages (*.org files). 

file:images/wiki-dired.png 

 - 5. =M-x org/wiki-dired-all= Open the org-wiki directory showing all
   files. 

file:images/wiki-dired-all.png 

 - 6. =M-x org-wiki/search-pattern= Search for all wiki page that contains
   a pattern. (string or regex pattern). 

Example: The command =M-x org-wiki/search-patern - System.Windows= will search all
files that contains "System.Windows string".

file:images/wiki-search-pattern.png
** Demos 

 - (1) Browsing org-wiki 

#+BEGIN_HTML
<video src="https://zippy.gfycat.com/LimitedValuableJellyfish.webm" controls>
</video>
#+END_HTML


 - (2) Wiki directory. M-x wiki-dired 

#+BEGIN_HTML
<video src="https://zippy.gfycat.com/SentimentalSlightAlpineroadguidetigerbeetle.webm" controls>
</video>
#+END_HTML


 - (3) M-x org-wiki/helm - Select a wiki page by name. 

#+BEGIN_HTML
<video src="https://zippy.gfycat.com/ImpracticalAnimatedEnglishsetter.webm" controls>
</video>
#+END_HTML

 - (4) M-x org-wki/search-pattern 

#+BEGIN_HTML
<video src="https://zippy.gfycat.com/MeatyBitterBonobo.webm" controls>
</video>
#+END_HTML

 - (5) M-x org-wiki/insert  Insert a wiki page link at point. 

#+BEGIN_HTML
<video src="https://zippy.gfycat.com/DistantGeneralIndianglassfish.webm" controls>
</video>
#+END_HTML
 
