#+INCLUDE: theme/style.org
#+TITLE: org-wiki 
#+AUTHOR: Caio Rodrigues 

* Org-wiki 
** Overview 

Org-wiki is a wiki built over org-mode. It provides many functions to
keep a wiki and several notes.

It provides a custom protocol ~wiki:keyword~ which creates like. When
clicked this links creates the wiki file in the wiki diretory with
name ~keyword.org~.

Link formats:

 - =wiki:<pagename>=

 - =wiki-asset-sys:<pagename>/<asset file name>=

Example: the link 

#+BEGIN_SRC org
     wiki-asset-sys:Linux;LearnLinux.pdf
or 
     [[wiki-asset-sys:Linux;LearnLinux.pdf]]
or
     [[wiki-asset-sys:Linux;LearnLinux.pdf][Book Learn Linux.pdf]]
#+END_SRC

will open the file ~~/wiki-directory/Linux/LearnLinux.pdf~ with the
default system application.


Features:

 - A wiki system for Emacs.

 - Command to export all pages to html without block Emacs.

 - Helm interface to search wiki pages.

 - Almost self-contained and with few dependencies.

 - 

# - Command to paste images (Only works in Linux for now and requires Xclip);

** Commands

  - =M-x org-wiki/index= - Open the index page. It opens the file
    index.org that is the first default page of the wiki. If the file
    doesn't exist it will be created.


  - =M-x org-wiki/index-frame= - Open the wiki index page in a new frame.


  - =M-x org-wiki/helm= - Open a helm interface to search the wiki
    page.

  
  - =M-x org-wiki/helm-frame= - Open a wiki page in a new frame. 


  - =M-x org-wiki/make-page= - Creates a new wiki page asking the user
    for the page name.


  - =M-x org-wiki/helm-assets= - Select a wiki page and open its
    assets directory.


  - =M-x org-wiki/dired= - Open the wiki directory in Emacs
    dired-mode showing only *.org files.


  - =M-x org-wiki/dired-all= - Open the wiki directory in Emacs
    showing all files. 


  - =M-x org-wiki/close= - Close all wiki pages.


  - =M-x org-wiki/insert= - Inserts a org-mode link at current point
    to a Wiki page selected through a helm-menu.
 

  - =M-x org-wiki/export-html-async= - Exports all wiki pages to html
    asynchronously, it means withoyt block Emacs by starting a new
    Emacs process in background.
** Setup 

1. Install helm 


2. Copy the package to the desired location. 


#+BEGIN_SRC 
mkdir -p ~/.emacs.d/packages/ 
git clone <org-wiki-url>
#+END_SRC


3. Add to init file ~/.emacs.d/init.el or ~/.emacs 

#+BEGIN_SRC elisp 
(add-to-list 'load-path "~/.emacs.d/packages/org-wiki")
(require 'org-wiki)
(setq org-wiki/location "~/org/wiki")

#+END_SRC



** Screenshots 

 - 1. Command =M-x org-wiki/index= Open the wiki index page (file index.org) 

file:images/org-wiki-index.png

 - 2. Command =M-x org-wiki/helm= Open a helm menu to select the wiki
   page to be opened. 

file:images/wiki-helm-command.png 

 - 3. =M-x org-wiki/ [tab]= provides easy completion and
   discoverability to org-wiki commands. 

file:images/autocompletion.png 



